### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by techpeace** [samhiatt/node-hue-emulator#1]
Hi there! Just ran across this, great work!

I was hoping you might consider [adding an Open Source license](http://choosealicense.com) so that folks can contribute back to the project.

Thanks again!

**Comment by samhiatt** [comment]
Thanks for the suggestion. I've added a license. 

I look forward to your feedback and contributions!

**Comment by techpeace** [comment]
Great, thanks so much!
